name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: |
          icacls gradlew /grant Everyone:RX

      - name: Build with Gradle
        run: |
          .\gradlew assembleDebug lintVitalRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 10